### ISSUE TITLE
packageinstall via checkbox

### ISSUE THREAD

**Issue by aparcar** [aparcar/jefe#18]
add popular (or soon popular) packages via a checkbox should be supported

- luci
- luci-app-attendedsysupgrade
- what_else?

**Comment by markbirss** [comment]
Here are some suggestions for USB Lan and USB Wifi Adaptors for Single Board Computer Builds ie 
needed to do mesh since on-board wifi either not supported or cant do mesh

Raspberry Pi (bcm2708/bcm2709/bcm2710)
and
Orange Pi - Xunlong Orange Pi Plus  

USB Wifi
* kmod-rt73-usb
* kmod-rt2800-lib
* kmod-rt2800-usb
* kmod-rt2x00-lib
* kmod-rt2x00-usb

USB Lan
* kmod-usb-net-mcs7830
* kmod-usb-net-asix
* kmod-usb-net-asix-ax88179
* kmod-usb-net-dm9601-ether

**Comment by aparcar** [comment]
@dangowrt should I create a list of suggestions that automatically pops up when a fitting target/subtarget is selected?

**Comment by aparcar** [comment]
This is for now solved by flavors, if there is a real need for additional packages feel free to comment here and I'll reopen the issue
